# Generated by Django 4.2.10 on 2024-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=40)),
                ('email', models.TextField()),
                ('password', models.TextField(max_length=10)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
